baseURL: https://example.com/
defaultContentLanguage: de
languageCode: de-DE
theme: hand-theme

taxonomies:
  tag: tags
  category: categories
  languages: languages

markup:
  goldmark:
    renderer:
      unsafe: true
