name = "HAND Theme"
license = "MIT"
licenselink = "https://github.com/hand-group/hand-theme/blob/master/LICENSE"
description = "Custom hugo theme for H.AND GROUP websites."
homepage = "https://github.com/hand-group/hand-theme"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "akmann"
  homepage = "https://akmnn.de"
